config/routes.rb
Rails.application.routes.draw do

root 'people#index'

resources :people

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/person.rb
class Person < ApplicationRecord
validates_presence_of :first_name, :last_name, :age, :hair_color, :eye_color, :gender

  def full_name
    "#{first_name} #{last_name}"
  end

  def description
    " is #{age} years old, is #{gender}, has #{hair_color} hair, and has #{eye_color} eyes"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController

before_action :set_person, only: [:show, :update, :edit, :destroy]

  def index
    @people = Person.all
  end

  def show
    @full_name = @person.full_name
    @description = @person.description
  end

  def new
    @person = Person.new
    render partial: "form"
  end

  def create
    person = Person.new(person_params)
    if person.save
      redirect_to person_path(person)
    else
      render partial: "form"
    end
  end

  def edit
    render partial: "form"
  end

  def update
    if @person.update(person_params)
      redirect_to person_path(@person)
    else
      render partial: "form"
    end
  end

  def destroy
    @person.destroy
    redirect_to people_path
  end

private
  def set_person
    @person = Person.find(params[:id])
  end

  def person_params
    params.require(:person).permit(:first_name, :last_name, :age, :hair_color, :eye_color, :gender)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PeopleProject</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= render partial: 'shared/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/people/_form.html.erb
<h1><%= @person.id ? 'Edit Person' : 'Create Person' %></h1>
<hr>
<%= form_for @person do |f| %>
  <%= f.label :first_name %>
  <%= f.text_field :first_name, required: true, autofocus: true %>
  <br>
  <%= f.label :last_name %>
  <%= f.text_field :last_name, required: true %>
  <br>
  <%= f.label :age %>
  <%= f.number_field :age, required: true %>
  <br>
  <%= f.label :gender %>
  <%= f.text_field :gender %>
  <br>
  <%= f.label :hair_color %>
  <%= f.text_field :hair_color, required: true %>
  <br>
  <%= f.label :eye_color %>
  <%= f.text_field :eye_color, required: true %>
  <br>
  <%= f.submit %>
<% end %>

app/views/people/index.html.erb
<h1>All the people.</h1>
<%= link_to 'Create a New Person', new_person_path %>
<% @people.each do |person| %>
  <h3><%= link_to "#{person.full_name}", person_path(person) %><h3>
    <%= link_to 'Delete', @person, method: :delete %>
  <br>
<% end %>

app/views/people/show.html.erb
<h1><%= @full_name %></h1>
<p><%= @full_name %> <%= @description %></p>
<%= link_to 'Edit', edit_person_path, class: "ui grey button" %>
<%= link_to 'Back', people_path %>

app/views/shared/_navbar.html.erb
<div class="ui menu">
  <div class="header item">
  </div>
<%= link_to 'Home', people_path, class: "ui blue button" %>
  <a class="item">

  </a>
  <a class="item">

  </a>
</div>